language: node_js
node_js:
- '4.1'
before_script:
- gem update --system
- gem install sass
- gem install compass
env:
  global:
  - secure: YF40rlP9kLceuS4RVIycVARokIrY5MLdVKpYakbAqwDye+fuExIfYVz4lZp3uGoG0+O/Fe97yAuVHrfFemH0/tEjts2a1/nfl05ueZDXbHzUSBW1/i/9Hu/k2EhdjExaesq0xo6Ap9Loicia7X0qaMoavNa4DT1Py9Exuq6kj80=
  - secure: bM6iWiz4P1tMG1vphHjIenuB7MuU3VGSPpOFri69ESnxQX+O2bLRzV1nZIpoKOiE9DS+8bGMCcFr3OLaahmhpBMtdhTvZGkcIGVbX0Egm56/QF0g+2gtBSHomEpFicIy+UUTlqkcs8wuth7xmA+AQUEr/IMz3O4pnatrPbjVzwg=
addons:
  sauce_connect: true
sudo: false