language: node_js
node_js:
- '0.10'
before_script:
- gem update --system
- gem install sass
- gem install compass
env:
  global:
  - secure: RYKefsqSJACQJVHcMoA6cz6+lZYbkgoI2wAa+qK5qPFoUQoMRbNVO0tjjBXgc65dLh/r0mnb17ES4xqbsp9yXfknkumHBpDePT6sY4m/rJWdZsW3fs4IFGxyTsYz5TNMmypDyOcL7zgc24e1DaaBiR2kT+UlU25zfUIZo2fzrZs=
  - secure: m3DoknoFa36DuFarOpXoEwcKidGkYFQfRqeG/CqBHB7l3DOSZUrauvAnOjl8qj+HuEy6vIsWB2Dyk4VtPL2+RJW0Z/wIvfLQJsPtdNyvBBTc3iCj3cXZeXBhG+0LcH8WeJH8PNBNfVmXnGkAyijbcdA5iD2mTcRFHWkK2I8TXCI=
addons:
  sauce_connect: true
